apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: decrypt
  name: decrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decrypt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: decrypt
    spec:
      containers:
      - env:
        - name: jsonfilename
          valueFrom:
            configMapKeyRef:
              key: jsonfilename
              name: env-file
        - name: testvar3
          valueFrom:
            configMapKeyRef:
              key: testvar3
              name: env-file
        - name: testvar4
          valueFrom:
            configMapKeyRef:
              key: testvar4
              name: env-file
        - name: testvar5
          valueFrom:
            configMapKeyRef:
              key: testvar5
              name: env-file
        image: 'decrypt:latest'
        imagePullPolicy: ""
        name: decrypt
        resources: {}
        volumeMounts:
        - mountPath: /outputdata
          name: outputdatavolume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: outputdatavolume
        persistentVolumeClaim:
          claimName: outputdatavolume
status: {}
