FROM python:3
#WORKDIR /code
RUN pip install cryptography
RUN pip install json2xml
#do not copy anything in - let the bind mount provide the required files
#COPY ./requirements.txt requirements.txt
COPY ./encrypt.py encrypt.py
#RUN python -m pip install
#change this and use a bash script to run
CMD [ "python", "encrypt.py" ]