apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: encrypt
  name: encrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: encrypt
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: encrypt
    spec:
      containers:
      - env:
        - name: jsonfilename
          valueFrom:
            configMapKeyRef:
              key: jsonfilename
              name: env-file
        - name: testvar3
          valueFrom:
            configMapKeyRef:
              key: testvar3
              name: env-file
        - name: testvar4
          valueFrom:
            configMapKeyRef:
              key: testvar4
              name: env-file
        - name: testvar5
          valueFrom:
            configMapKeyRef:
              key: testvar5
              name: env-file
        image: '0872/encrypt:'
        imagePullPolicy: ""
        name: encrypt
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
