apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-31T17:30:27Z"
  name: nginx-service3
spec:
  type: NodePort
  ports:
  - nodePort: 31317
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
